version: '2'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: signalement
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
  web:
    image: php
    environment:
      DATABASE_URL: "postgresl://signalement:mysecretpassword@localhost/signalement"
    volumes:
     - .:/code
    working_dir: /code
    command: php -S localhost:9010
    ports: 
     - "9010:9010"
    links:
     - db